app:
  name: "bluebell"
  mod: "dev"
  port: 8081
log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: 123
  dbname: "bluebell"
redis:
  host: "127.0.0.1"
  port: 6379